### ISSUE TITLE
Feature request | Send the invoice by mail

### ISSUE THREAD

**Issue by You85** [Invoicebus/html-invoice-generator#6]
Hello,
It would be interesting to allow users to send the invoice by e-mail in pdf format.
Thanks You.

**Comment by imjustd** [comment]
In order to make that functionality, we must use some server-side processing, but our goal was to make the invoice generator platform independent and work without any additional software. That's why the invoice generator doesn't use any server-side scripting, just a plain JavaScript code. So adding that functionality will break our paradigm for platform independence. Now it works on any platform Mac or PC, desktop or mobile.
